experiment: exp4_debug

stages:
  - &vision1
    name: vision1_exp4_debug
    batch_size: 2
    grad_accum_steps: 1
    lr: 0.0001
    epochs: 1
    lora_r: 2
    lora_alpha: 4
    lora_dropout: 0.1
    regex_targets:
      - "visual\\.blocks\\.\\d+\\.attn\\.qkv"
      # - "visual\\.blocks\\.\\d+\\.attn\\.proj"
    resume_strategy: "checkpoint"

  - &vision2
    name: vision2_exp4_debug
    batch_size: 2
    grad_accum_steps: 1
    lr: 0.0001
    epochs: 1
    lora_r: 2
    lora_alpha: 4
    lora_dropout: 0.1
    regex_targets:
      - "visual\\.blocks\\.\\d+\\.attn\\.qkv"
      # - "visual\\.blocks\\.\\d+\\.attn\\.proj"
    resume_strategy: "stage"

debug:
  dataset_subset: 8
  wandb_suffix: "-debug"
  wandb_tags: ["debug"]
